import "server-only";

import { mkdir, readFile, writeFile, unlink } from "node:fs/promises";
import { dirname, normalize, resolve, sep } from "node:path";

import { env, isProduction } from "@/server/env";

/**
 * Object storage.
 *
 * Two drivers behind one interface: the local filesystem in development, Vercel
 * Blob in production. Business logic never knows which.
 *
 * Private objects — child photographs — are never given a public URL by either
 * driver. They are read back through an authorised route, and a database CHECK
 * refuses to record a public URL against a private object.
 */

export interface StoredObject {
  storageKey: string;
  /** Only ever set for public objects. */
  publicUrl: string | null;
}

export interface StorageDriver {
  readonly name: string;
  put(key: string, bytes: Uint8Array, contentType: string, visibility: "PUBLIC" | "PRIVATE"): Promise<StoredObject>;
  get(key: string): Promise<Uint8Array | null>;
  delete(key: string): Promise<void>;
}

/**
 * Where the local driver keeps files. Outside `public/`, deliberately.
 *
 * Relative, so it resolves against the PROCESS working directory — normally the
 * project root, but not if something starts `next dev` from elsewhere. Worth
 * knowing when hunting for a development upload: the bytes follow the process,
 * not the repository. Production uses the Blob driver and never touches this.
 */
export const LOCAL_STORAGE_DIR = ".storage";

/**
 * Local filesystem driver for development.
 *
 * Files live outside `public/` so that nothing here is served by the static
 * handler — a child photograph must never be reachable by guessing a URL. Even
 * "public" objects go through the application in development.
 */
export class LocalStorageDriver implements StorageDriver {
  readonly name = "local";

  /**
   * Resolves a key to a path inside the storage root, refusing anything that
   * escapes it. Keys are generated by us, but a path-traversal guard on a
   * filesystem write is not the place to rely on that.
   */
  private resolveKey(key: string): string {
    const root = resolve(LOCAL_STORAGE_DIR);
    const target = resolve(root, normalize(key));

    if (target !== root && !target.startsWith(root + sep)) {
      throw new Error("Storage key escapes the storage root");
    }
    return target;
  }

  async put(
    key: string,
    bytes: Uint8Array,
    _contentType: string,
    visibility: "PUBLIC" | "PRIVATE",
  ): Promise<StoredObject> {
    const path = this.resolveKey(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);

    return {
      storageKey: key,
      // Served through /api/media/[id] in both cases locally, so there is no
      // direct URL to leak.
      publicUrl: visibility === "PUBLIC" ? `/api/media/by-key/${encodeURIComponent(key)}` : null,
    };
  }

  async get(key: string): Promise<Uint8Array | null> {
    try {
      return new Uint8Array(await readFile(this.resolveKey(key)));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.resolveKey(key));
    } catch {
      // Already gone is the desired end state.
    }
  }
}

/**
 * Vercel Blob driver.
 *
 * **The production store is private, and a Blob store's access mode is fixed
 * when it is created.** "Private storage requires a private Blob store" — the
 * mode is not a per-upload choice, whatever the `access` argument on `put()`
 * suggests. A public store would hand out a CDN URL for every byte in it,
 * including a child's photograph, so there is one store and it is private.
 *
 * That leaves nowhere for a PUBLIC object to go, which is fine: no upload
 * purpose asks for one any more, and nothing in the application ever rendered
 * `publicUrl`. Every image — a child's photograph, a book cover, the library's
 * logo — is served through `/api/media/[id]`, which already answers a
 * signed-out request for a logo and answers nothing else.
 */
export class BlobStorageDriver implements StorageDriver {
  readonly name = "vercel-blob";

  async put(
    key: string,
    bytes: Uint8Array,
    contentType: string,
    visibility: "PUBLIC" | "PRIVATE",
  ): Promise<StoredObject> {
    if (visibility === "PUBLIC") {
      // Refuse rather than silently store it privately and hand back a URL that
      // will not resolve. If a public object is ever genuinely needed it needs
      // its own public store and its own credential, which is a decision, not
      // a fallback.
      throw new Error(
        "The production Blob store is private: a PUBLIC object has no store to go to",
      );
    }

    const { put } = await import("@vercel/blob");

    const result = await put(key, Buffer.from(bytes), {
      access: "private",
      contentType,
      token: env.BLOB_READ_WRITE_TOKEN,
      addRandomSuffix: false,
    });

    return { storageKey: result.pathname, publicUrl: null };
  }

  /**
   * Reads bytes back.
   *
   * This used to call `head()` and then `fetch` the URL it returned. That is
   * correct for a public blob and wrong for a private one: a private blob's URL
   * "is not publicly accessible", so the fetch would have failed and every
   * child's photograph would have 404ed in production while rendering perfectly
   * in development. `get()` is the documented private read and carries the
   * credential itself.
   */
  async get(key: string): Promise<Uint8Array | null> {
    const { get } = await import("@vercel/blob");

    try {
      const result = await get(key, {
        access: "private",
        token: env.BLOB_READ_WRITE_TOKEN,
      });

      if (!result || result.statusCode !== 200) return null;
      return new Uint8Array(await new Response(result.stream).arrayBuffer());
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    const { del } = await import("@vercel/blob");
    try {
      await del(key, { token: env.BLOB_READ_WRITE_TOKEN });
    } catch {
      // Already gone is the desired end state.
    }
  }
}

let cachedDriver: StorageDriver | null = null;

/**
 * Chooses the driver. Split from `storage()` so the production rule can be
 * tested without a production process.
 *
 * The old version fell back to the local driver whenever the Blob token was
 * absent, production or not. On a serverless platform that means a child's
 * photograph is written to a container's own disk: it succeeds, the row points
 * at a key, and the bytes are gone by the next request — a photograph that
 * exists in the database and nowhere else, discovered by a family, not by us.
 * There is no safe fallback for that, so there is no fallback.
 */
export function selectStorageDriver(
  production: boolean,
  blobToken: string | undefined,
): StorageDriver {
  if (!production) return new LocalStorageDriver();

  if (!blobToken) {
    throw new Error(
      "BLOB_READ_WRITE_TOKEN is not set: link a Vercel Blob store before deploying. " +
        "Refusing to store uploads on a filesystem that does not survive the request.",
    );
  }

  return new BlobStorageDriver();
}

export function storage(): StorageDriver {
  cachedDriver ??= selectStorageDriver(isProduction, env.BLOB_READ_WRITE_TOKEN);
  return cachedDriver;
}

/** Test seam. */
export function __setStorageDriverForTests(driver: StorageDriver | null): void {
  cachedDriver = driver;
}
