import "server-only";

import { mkdir, readFile, writeFile, unlink } from "node:fs/promises";
import { dirname, normalize, resolve, sep } from "node:path";

import { env, isProduction } from "@/server/env";

/**
 * Object storage.
 *
 * Two drivers behind one interface: the local filesystem in development, Vercel
 * Blob in production. Business logic never knows which.
 *
 * Private objects — child photographs — are never given a public URL by either
 * driver. They are read back through an authorised route, and a database CHECK
 * refuses to record a public URL against a private object.
 */

export interface StoredObject {
  storageKey: string;
  /** Only ever set for public objects. */
  publicUrl: string | null;
}

export interface StorageDriver {
  readonly name: string;
  put(key: string, bytes: Uint8Array, contentType: string, visibility: "PUBLIC" | "PRIVATE"): Promise<StoredObject>;
  get(key: string): Promise<Uint8Array | null>;
  delete(key: string): Promise<void>;
}

/**
 * Where the local driver keeps files. Outside `public/`, deliberately.
 *
 * Relative, so it resolves against the PROCESS working directory — normally the
 * project root, but not if something starts `next dev` from elsewhere. Worth
 * knowing when hunting for a development upload: the bytes follow the process,
 * not the repository. Production uses the Blob driver and never touches this.
 */
export const LOCAL_STORAGE_DIR = ".storage";

/**
 * Local filesystem driver for development.
 *
 * Files live outside `public/` so that nothing here is served by the static
 * handler — a child photograph must never be reachable by guessing a URL. Even
 * "public" objects go through the application in development.
 */
export class LocalStorageDriver implements StorageDriver {
  readonly name = "local";

  /**
   * Resolves a key to a path inside the storage root, refusing anything that
   * escapes it. Keys are generated by us, but a path-traversal guard on a
   * filesystem write is not the place to rely on that.
   */
  private resolveKey(key: string): string {
    const root = resolve(LOCAL_STORAGE_DIR);
    const target = resolve(root, normalize(key));

    if (target !== root && !target.startsWith(root + sep)) {
      throw new Error("Storage key escapes the storage root");
    }
    return target;
  }

  async put(
    key: string,
    bytes: Uint8Array,
    _contentType: string,
    visibility: "PUBLIC" | "PRIVATE",
  ): Promise<StoredObject> {
    const path = this.resolveKey(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);

    return {
      storageKey: key,
      // Served through /api/media/[id] in both cases locally, so there is no
      // direct URL to leak.
      publicUrl: visibility === "PUBLIC" ? `/api/media/by-key/${encodeURIComponent(key)}` : null,
    };
  }

  async get(key: string): Promise<Uint8Array | null> {
    try {
      return new Uint8Array(await readFile(this.resolveKey(key)));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.resolveKey(key));
    } catch {
      // Already gone is the desired end state.
    }
  }
}

/**
 * Vercel Blob driver.
 *
 * Private objects use `access: "private"`, so the stored key is not a URL that
 * anyone can fetch. Public objects (book covers, the library logo) get a real
 * CDN URL — they are pictures of books, not of children.
 */
export class BlobStorageDriver implements StorageDriver {
  readonly name = "vercel-blob";

  async put(
    key: string,
    bytes: Uint8Array,
    contentType: string,
    visibility: "PUBLIC" | "PRIVATE",
  ): Promise<StoredObject> {
    const { put } = await import("@vercel/blob");

    const result = await put(key, Buffer.from(bytes), {
      access: visibility === "PUBLIC" ? "public" : ("private" as "public"),
      contentType,
      token: env.BLOB_READ_WRITE_TOKEN,
      addRandomSuffix: false,
    });

    return {
      storageKey: result.pathname,
      publicUrl: visibility === "PUBLIC" ? result.url : null,
    };
  }

  async get(key: string): Promise<Uint8Array | null> {
    const { head } = await import("@vercel/blob");

    try {
      const meta = await head(key, { token: env.BLOB_READ_WRITE_TOKEN });
      const response = await fetch(meta.url);
      if (!response.ok) return null;
      return new Uint8Array(await response.arrayBuffer());
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    const { del } = await import("@vercel/blob");
    try {
      await del(key, { token: env.BLOB_READ_WRITE_TOKEN });
    } catch {
      // Already gone is the desired end state.
    }
  }
}

let cachedDriver: StorageDriver | null = null;

export function storage(): StorageDriver {
  cachedDriver ??=
    isProduction && env.BLOB_READ_WRITE_TOKEN
      ? new BlobStorageDriver()
      : new LocalStorageDriver();
  return cachedDriver;
}

/** Test seam. */
export function __setStorageDriverForTests(driver: StorageDriver | null): void {
  cachedDriver = driver;
}
