-- ===========================================================================
-- Phase 4 — reminders, and a child asking to keep a book.
--
-- Generated by `prisma migrate diff`, then hand-extended with three things the
-- generator cannot know about:
--
--   1. **A guard, before anything else.** The new partial unique index says a
--      loan may have at most one PENDING renewal request. If a database somehow
--      already holds two, this migration refuses rather than choosing which one
--      to keep. Deleting a child's request to make an index build is exactly
--      the kind of silent repair Phase 3 taught us not to write. In practice no
--      such row exists anywhere — the table has never been written to — so on
--      every real database this step does nothing at all.
--
--   2. **The partial unique index itself**, which is not expressible in
--      schema.prisma and therefore never appears in a generated diff. It is the
--      thing that makes "ask twice at once" impossible, rather than merely
--      unlikely. Also recorded in prisma/sql/006_notifications_and_renewals.sql.
--
--   3. **The new permission and its grants.** `loan.request_renewal` is what a
--      child holds to ask; without it in the database, an already-deployed
--      library would upgrade to a Phase 4 that no reader can use until somebody
--      remembers to re-run the seed. Written idempotently, granted only to the
--      roles that should have it, and re-derived by the seed on every run.
--
-- Nothing here deletes, rewrites or invents a row. `loan_notification` starts
-- empty, which correctly means "no family has been written to yet".
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 0. Refuse to build the index over data that contradicts it.
-- ---------------------------------------------------------------------------
DO $$
DECLARE v_count integer; v_loans text;
BEGIN
  SELECT count(*), string_agg(loan_id, ', ' ORDER BY loan_id)
    INTO v_count, v_loans
    FROM (
      SELECT loan_id
        FROM renewal_request
       WHERE status = 'PENDING'
       GROUP BY loan_id
      HAVING count(*) > 1
    ) AS duplicated;

  IF coalesce(v_count, 0) = 0 THEN RETURN; END IF;

  RAISE EXCEPTION
    'Cannot enable renewal requests: % loan(s) already have more than one pending request (%). Someone must decide which request stands; a deployment must not pick one and discard the rest. See docs/OPERATIONS.md, "More than one pending renewal request".',
    v_count, v_loans USING ERRCODE = 'raise_exception';
END $$;

-- ---------------------------------------------------------------------------
-- 1. Reminders (generated).
-- ---------------------------------------------------------------------------

-- CreateEnum
CREATE TYPE "LoanNotificationKind" AS ENUM ('DUE_SOON', 'OVERDUE');

-- CreateTable
CREATE TABLE "loan_notification" (
    "id" TEXT NOT NULL,
    "library_id" TEXT NOT NULL,
    "loan_id" TEXT NOT NULL,
    "kind" "LoanNotificationKind" NOT NULL,
    "due_at" TIMESTAMPTZ(6) NOT NULL,
    "offset_days" INTEGER NOT NULL,
    "status" "EmailStatus" NOT NULL DEFAULT 'QUEUED',
    "claimed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sent_at" TIMESTAMPTZ(6),
    "email_event_id" TEXT,

    CONSTRAINT "loan_notification_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "loan_notification_library_id_claimed_at_idx" ON "loan_notification"("library_id", "claimed_at");

-- CreateIndex
--
-- The whole of duplicate prevention. One row per (loan, due date, occurrence):
-- a second run of the daily job, or two runs at the same instant, collide here
-- instead of writing a second email to a family.
CREATE UNIQUE INDEX "loan_notification_occurrence_key" ON "loan_notification"("loan_id", "due_at", "offset_days");

-- AddForeignKey
ALTER TABLE "loan_notification" ADD CONSTRAINT "loan_notification_library_id_fkey" FOREIGN KEY ("library_id") REFERENCES "library"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "loan_notification" ADD CONSTRAINT "loan_notification_loan_id_fkey" FOREIGN KEY ("loan_id") REFERENCES "loan"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- 2. One pending renewal request per loan.
--
--    Partial, so a loan can accumulate any number of DECIDED requests over its
--    life — asking again after a no is allowed, and the history of both asks is
--    kept — while only one can be open at a time.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "renewal_request_one_pending_per_loan"
    ON "renewal_request" ("loan_id")
 WHERE "status" = 'PENDING';

-- ---------------------------------------------------------------------------
-- 3. The permission a child holds to ask.
--
--    Granted to readers and to Super Admin. NOT granted to Librarian or Junior
--    Librarian: staff renew at the desk with `loan.renew`, and a librarian
--    raising a request in a child's name would put words in their mouth.
-- ---------------------------------------------------------------------------
INSERT INTO "permission" ("key", "category", "description")
VALUES (
  'loan.request_renewal',
  'circulation',
  'Ask a librarian to keep a book you have borrowed for longer'
)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO "role_permission" ("role_id", "permission_key")
SELECT r."id", 'loan.request_renewal'
  FROM "role" r
 WHERE r."key" IN ('MEMBER', 'SUPER_ADMIN')
ON CONFLICT DO NOTHING;
